# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 04aab8a577fe5ce1a5e394a04146703551ee6c038fd0c20a223e1ac31103583c5f8b49599f2c1b58af8c11c3ce51236cad5d62071b4aef4fe24efcbffc0615a9

test:
  secret_key_base: 37bcb16a1ef5d9e834e3495089e59755596131bca9395c86217eec61c13123a2ba41f408f2f33fe0d98c5844ff6e2c31c7f9f7c40f36d3bc86b7234fb105e5a4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
